### ISSUE TITLE
Identify Cloud provider for app

### ISSUE THREAD

**Issue by abbiefarr** [CityOfDetroit/affordable-housing-app#70]
This is only relevant if we go "full Bloom" (if we use decoupled Drupal we'll be using Acquia). We need to know from the city which Cloud provider they want to go with so we can set up a proper deployment pipeline.

**Comment by willrlin** [comment]
I'm going to close this, since we're not blocked on it and once they tell us which one, we'll then create some tasks for setting up the deployment pipeline to that service.
