### ISSUE TITLE
Figure out which repo we should use

### ISSUE THREAD

**Issue by avaleske** [CityOfDetroit/affordable-housing-app#73]
Should we work in the forked bloom repo, or the affordable-housing-app repo?

Are their implications for searching our fork? What about pulling in upstream changes?

**Comment by anders-schneider** [comment]
*Sigh* in addition to not being searchable via the search bar...

![image](https://user-images.githubusercontent.com/8754454/121538484-d17edf00-c9d2-11eb-8aaf-1f9a1e5213f4.png)

... our forked repo doesn't have the little tooltip that links to where something is defined/referenced:

![image](https://user-images.githubusercontent.com/8754454/121538730-01c67d80-c9d3-11eb-9275-037fc1704400.png)

(I'm not suggesting that this should be a big factor in which repo we use, just wanted to note this somewhere for posterity.)
