### ISSUE TITLE
Get a list of the services Bloom depends on

### ISSUE THREAD

**Issue by avaleske** [CityOfDetroit/affordable-housing-app#82]
Bloom depends on a number of other services, such as sendgrid, mapbox, and others. It'd be helpful to have a list of these services, so we can figure out which Detroit already has a license for, which we'll need to swap out with others, and which we'll need to remove entirely.

Done: We have a list of services that Bloom depends on that we can send to DoIT

**Comment by willrlin** [comment]
Some things I've encountered already:
Cloudinary for image uploading
Redis for load distribution on the DB
Seems like they deploy both the backend/core and DB to Heroku, but if we deploy them separately (like in GCP), they'd be separate fees. And the private connector to hook backend/core - redis - cloud SQL is also a separate fee.

**Comment by willrlin** [comment]
They also use CircleCI for integration.

**Comment by willrlin** [comment]
I just asked about this here: https://github.com/bloom-housing/bloom/discussions/1400

**Comment by willrlin** [comment]
That seems to be it, response here:
https://github.com/bloom-housing/bloom/discussions/1400#discussioncomment-917856
