### ISSUE TITLE
Define data model

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/affordable-housing-app#9]
Look at Bloom fields and fields available in Rebecca's spreadsheet and define how we want to structure our data.

Done: Have an approved proposal for our data model. Does not include actually configuring a database

**Comment by anders-schneider** [comment]
Note: this is the spreadsheet referenced in the description above: https://app.box.com/integrations/googledss/openGoogleEditor?fileId=810556084343&trackingId=3#gid=0

**Comment by anders-schneider** [comment]
Created a doc to detail the Bloom data model (https://detroitmigov.box.com/s/w85hw5svetu2hlj6xrvsa7nn0j2o2dsw). I'll reference that in my proposal doc so that we're explicit about where our data model aligns with and differs from Bloom's.

**Comment by anders-schneider** [comment]
Sent out a proposal doc: https://detroitmigov.box.com/s/bzanpmt2xffegig9sjz4gom6oopme2yo (it has two different proposals, based on whether we choose Drupal or Bloom as our starting point)

**Comment by anders-schneider** [comment]
We talked about the proposal in yesterday's design review and "approved" it. There are still comments in the doc that I'll go through and address, but I'll close this since we've met the "done criteria".
